// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    key_id,
    tenant_id,
    user_id,
    name,
    key_hash,
    status,
    expires_at,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, key_id, tenant_id, user_id, name, key_hash, status, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateAPIKeyParams struct {
	KeyID     uuid.UUID        `json:"key_id"`
	TenantID  uuid.UUID        `json:"tenant_id"`
	UserID    uuid.UUID        `json:"user_id"`
	Name      string           `json:"name"`
	KeyHash   string           `json:"key_hash"`
	Status    ApiKeyStatus     `json:"status"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedBy *string          `json:"created_by"`
	UpdatedBy *string          `json:"updated_by"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyID,
		arg.TenantID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_id, tenant_id, user_id, name, key_hash, status, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM api_keys
WHERE key_hash = $1 AND deleted_at IS NULL AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, key_id, tenant_id, user_id, name, key_hash, status, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM api_keys
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, key_id, tenant_id, user_id, name, key_hash, status, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM api_keys
WHERE tenant_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAPIKeysParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKeys, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.TenantID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeys{}
	for rows.Next() {
		var i ApiKeys
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET
    status = 'revoked',
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, key_id, tenant_id, user_id, name, key_hash, status, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type RevokeAPIKeyParams struct {
	ID        uuid.UUID `json:"id"`
	DeletedBy *string   `json:"deleted_by"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.DeletedBy)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateAPIKeyStatus = `-- name: UpdateAPIKeyStatus :one
UPDATE api_keys
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, key_id, tenant_id, user_id, name, key_hash, status, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateAPIKeyStatusParams struct {
	ID        uuid.UUID    `json:"id"`
	Status    ApiKeyStatus `json:"status"`
	UpdatedBy *string      `json:"updated_by"`
}

func (q *Queries) UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, updateAPIKeyStatus, arg.ID, arg.Status, arg.UpdatedBy)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
