// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKeyStatus string

const (
	ApiKeyStatusActive  ApiKeyStatus = "active"
	ApiKeyStatusRotated ApiKeyStatus = "rotated"
	ApiKeyStatusRevoked ApiKeyStatus = "revoked"
	ApiKeyStatusExpired ApiKeyStatus = "expired"
)

func (e *ApiKeyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyStatus(s)
	case string:
		*e = ApiKeyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyStatus: %T", src)
	}
	return nil
}

type NullApiKeyStatus struct {
	ApiKeyStatus ApiKeyStatus `json:"api_key_status"`
	Valid        bool         `json:"valid"` // Valid is true if ApiKeyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyStatus), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusArchived  TenantStatus = "archived"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusPending   UserStatus = "pending"
	UserStatusSuspended UserStatus = "suspended"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type ApiKeys struct {
	ID        uuid.UUID        `json:"id"`
	KeyID     uuid.UUID        `json:"key_id"`
	TenantID  uuid.UUID        `json:"tenant_id"`
	UserID    uuid.UUID        `json:"user_id"`
	Name      string           `json:"name"`
	KeyHash   string           `json:"key_hash"`
	Status    ApiKeyStatus     `json:"status"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	CreatedBy *string          `json:"created_by"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	UpdatedBy *string          `json:"updated_by"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	DeletedBy *string          `json:"deleted_by"`
}

type TenantUsers struct {
	TenantID  uuid.UUID        `json:"tenant_id"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	CreatedBy *string          `json:"created_by"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	UpdatedBy *string          `json:"updated_by"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	DeletedBy *string          `json:"deleted_by"`
}

type Tenants struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Status    TenantStatus     `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	CreatedBy *string          `json:"created_by"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	UpdatedBy *string          `json:"updated_by"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	DeletedBy *string          `json:"deleted_by"`
}

type Users struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Fullname     string           `json:"fullname"`
	Status       UserStatus       `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	CreatedBy    *string          `json:"created_by"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	UpdatedBy    *string          `json:"updated_by"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	DeletedBy    *string          `json:"deleted_by"`
}
