// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (Users, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (Users, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
