// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) (TenantUsers, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKeys, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenants, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteTenant(ctx context.Context, arg DeleteTenantParams) (Tenants, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) (Users, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKeys, error)
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKeys, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenants, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenants, error)
	GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUsers, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (Users, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKeys, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenants, error)
	ListTenantsForUser(ctx context.Context, arg ListTenantsForUserParams) ([]Tenants, error)
	ListUsersInTenant(ctx context.Context, arg ListUsersInTenantParams) ([]Users, error)
	RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) (TenantUsers, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKeys, error)
	UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) (ApiKeys, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenants, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
