// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenant_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUserToTenant = `-- name: AddUserToTenant :one
INSERT INTO tenant_users (
    tenant_id,
    user_id,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (tenant_id, user_id) 
DO UPDATE SET 
    deleted_at = NULL,
    deleted_by = NULL,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by
RETURNING tenant_id, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type AddUserToTenantParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedBy *string   `json:"created_by"`
	UpdatedBy *string   `json:"updated_by"`
}

func (q *Queries) AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) (TenantUsers, error) {
	row := q.db.QueryRow(ctx, addUserToTenant,
		arg.TenantID,
		arg.UserID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TenantUsers
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTenantUser = `-- name: GetTenantUser :one
SELECT tenant_id, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tenant_users
WHERE tenant_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTenantUserParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUsers, error) {
	row := q.db.QueryRow(ctx, getTenantUser, arg.TenantID, arg.UserID)
	var i TenantUsers
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listTenantsForUser = `-- name: ListTenantsForUser :many
SELECT t.id, t.name, t.slug, t.status, t.created_at, t.created_by, t.updated_at, t.updated_by, t.deleted_at, t.deleted_by FROM tenants t
INNER JOIN tenant_users tu ON tu.tenant_id = t.id
WHERE tu.user_id = $1 AND tu.deleted_at IS NULL AND t.deleted_at IS NULL
ORDER BY tu.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTenantsForUser(ctx context.Context, arg ListTenantsForUserParams) ([]Tenants, error) {
	rows, err := q.db.Query(ctx, listTenantsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenants{}
	for rows.Next() {
		var i Tenants
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInTenant = `-- name: ListUsersInTenant :many
SELECT u.id, u.email, u.password_hash, u.fullname, u.status, u.created_at, u.created_by, u.updated_at, u.updated_by, u.deleted_at, u.deleted_by FROM users u
INNER JOIN tenant_users tu ON tu.user_id = u.id
WHERE tu.tenant_id = $1 AND tu.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY tu.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersInTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListUsersInTenant(ctx context.Context, arg ListUsersInTenantParams) ([]Users, error) {
	rows, err := q.db.Query(ctx, listUsersInTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Fullname,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTenant = `-- name: RemoveUserFromTenant :one
UPDATE tenant_users
SET
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $3
WHERE tenant_id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING tenant_id, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type RemoveUserFromTenantParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	DeletedBy *string   `json:"deleted_by"`
}

func (q *Queries) RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) (TenantUsers, error) {
	row := q.db.QueryRow(ctx, removeUserFromTenant, arg.TenantID, arg.UserID, arg.DeletedBy)
	var i TenantUsers
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
