// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name,
    slug,
    status,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, slug, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateTenantParams struct {
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	Status    TenantStatus `json:"status"`
	CreatedBy *string      `json:"created_by"`
	UpdatedBy *string      `json:"updated_by"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenants, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :one
UPDATE tenants
SET
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type DeleteTenantParams struct {
	ID        uuid.UUID `json:"id"`
	DeletedBy *string   `json:"deleted_by"`
}

func (q *Queries) DeleteTenant(ctx context.Context, arg DeleteTenantParams) (Tenants, error) {
	row := q.db.QueryRow(ctx, deleteTenant, arg.ID, arg.DeletedBy)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tenants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenants, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tenants
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenants, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tenants
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenants, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenants{}
	for rows.Next() {
		var i Tenants
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    name = COALESCE($3, name),
    slug = COALESCE($4, slug),
    status = COALESCE($5, status),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateTenantParams struct {
	ID        uuid.UUID        `json:"id"`
	UpdatedBy *string          `json:"updated_by"`
	Name      *string          `json:"name"`
	Slug      *string          `json:"slug"`
	Status    NullTenantStatus `json:"status"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenants, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.UpdatedBy,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
