// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    fullname,
    status,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, password_hash, fullname, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateUserParams struct {
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	Fullname     string     `json:"fullname"`
	Status       UserStatus `json:"status"`
	CreatedBy    *string    `json:"created_by"`
	UpdatedBy    *string    `json:"updated_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Fullname,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, fullname, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type DeleteUserParams struct {
	ID        uuid.UUID `json:"id"`
	DeletedBy *string   `json:"deleted_by"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, deleteUser, arg.ID, arg.DeletedBy)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, fullname, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, fullname, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($3, email),
    password_hash = COALESCE($4, password_hash),
    fullname = COALESCE($5, fullname),
    status = COALESCE($6, status),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, fullname, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	UpdatedBy    *string        `json:"updated_by"`
	Email        *string        `json:"email"`
	PasswordHash *string        `json:"password_hash"`
	Fullname     *string        `json:"fullname"`
	Status       NullUserStatus `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.UpdatedBy,
		arg.Email,
		arg.PasswordHash,
		arg.Fullname,
		arg.Status,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Fullname,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
